# Generated by Django 5.0.4 on 2024-04-20 10:48

import app.utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedditData',
            fields=[
                ('id', models.CharField(db_index=True, default=app.utils.utils.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('is_summarized', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, choices=[('news', 'news'), ('information', 'information'), ('other', 'other')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.CharField(db_index=True, default=app.utils.utils.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tweet_id', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('post_date', models.DateTimeField()),
                ('is_summarized', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, choices=[('news', 'news'), ('information', 'information'), ('other', 'other')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('id', models.CharField(db_index=True, default=app.utils.utils.get_char_uuid, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('is_summarized', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('flag', models.CharField(blank=True, choices=[('news', 'news'), ('information', 'information'), ('other', 'other')], max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
